name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to our repository! 🎉 We're glad you're here. If you have any questions or need help, feel free to ask!"
        pr-message: "Thank you for your first pull request! 🚀 We appreciate your contribution. If you need any assistance, don't hesitate to reach out!"
